<a href="https://colab.research.google.com/github/Anand2031/CSE2_Assignment/blob/main/20_TASK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as py

In [12]:
#1
import numpy as np
a = np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [28]:
#2
a = np.zeros((3,4))
a1 = np.ones((2,5))
print(a1)
print("\n",a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [33]:
#3
a = np.full((4,4),7)
print(a)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [37]:
#4
a = np.arange(1,13).reshape(3,4)
a2 = a.reshape(2,6)

print(a)
print(a2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [46]:
#5
a = np.arange(1,10).reshape([3,3])
print(a)
a1 = a.flatten()
print(a1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [48]:
#6
a = np.arange(10,51,5)
print(a)

[10 15 20 25 30 35 40 45 50]


In [55]:
#6
a = np.arange(10,51,10)
print(a)
a1 = np.sum(a[:3])
print(a1)

[10 20 30 40 50]
60


In [60]:
#7
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[6,5,4],[3,2,1]])
c = a+b
print(c)

[[7 7 7]
 [7 7 7]]


In [63]:
#9
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[6,5,4],[3,2,1]])
c = a-b
print(c)

[[-5 -3 -1]
 [ 1  3  5]]


In [62]:
#10
a = np.array([[1,2,3]])
b = np.array([[6,5,4]])
c = a * b
print(c)

[[ 6 10 12]]


In [64]:
#11
a = np.array([12,15,20,25,30])
mean = np.mean(a)
print(mean)

20.4


In [65]:
#12
a = np.array([12,15,20,25,30])
median = np.median(a)
print(median)

20.0


In [68]:
#13
a = np.array([12,15,20,25,30])
Sd = np.std(a)
print(Sd)

6.529931086925803


In [70]:
#14
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.sum(a,axis=1)
print(b)

[ 6 15 24]


In [71]:
#15
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.sum(a,axis=0)
print(b)

[12 15 18]


In [76]:
#16
a = np.arange(1,17).reshape(4,4)
a1 = np.mean(a,axis=1)
print(a1)

[ 2.5  6.5 10.5 14.5]


In [83]:
#17
a = np.ones([5,5])
print(a)
a1 = a.flatten()
print(a1)
print(a1.size)
print(a1.shape)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1.]
25
(25,)


In [85]:
#18
a = np.array([1,2,3,4,])
b = np.array([5,6,7,8])
c = (a + b) * 2
print(c)

[12 16 20 24]


In [89]:
#19\
a = np.arange(1,10).reshape(3,3)
b = a * 5

print(b)

c = b.sum()
print(c)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
225


In [90]:
#20
a = np.array([15, 18, 21, 24, 27, 30])
mean = np.mean(a)
print(mean)
median = np.median(a)
print(median)
Sd = np.std(a)
print(Sd)

22.5
22.5
5.123475382979799
